all: java python perl
java:
	javac FileConversion.java
	java FileConversion control-char.txt control-char-output-Java.txt
	@echo "\n"
python:
	python3 FileConversion.py control-char.txt control-char-output-Python.txt
	@echo "\n"
perl:
	perl FileConversion.pl control-char.txt control-char-output-Perl.txt